version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "50000:50000"
    expose:
      - 22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
